/**
 * ================================================================
 * SLI AUTOMATION
 * VERSION 1.3
 * ================================================================
 *
 * INPUT:
 * JSON generated by the Gemini Gem:
 * "SLI Data Preparation & Validation"
 *
 * OUTPUT:
 * 1. Completed native Google Doc
 * 2. Microsoft Word .docx
 * 3. PDF .pdf
 *
 * ================================================================
 * STATIC MASTER FIELDS - NEVER MODIFY
 * ================================================================
 *
 * The following fields are configured directly in:
 * "AIT SLI - AUTOMATION MASTER"
 *
 * The script MUST NEVER modify them:
 *
 * - Box 8  - Related Party Indicator
 * - Box 9  - Routed Export Transaction
 * - Box 10 - Hazardous Material
 * - Box 12 - Ultimate Consignee Type
 * - Box 15 - Carnet
 * - Box 16 - TIB
 * - Mode of Transport
 * - Incoterms 2020
 * - Box 30 - DDTC Applicant Registration Number
 * - Box 31 - Eligible Party Certification
 * - Box 32 - Low-value AES indicator
 * - Box 35 - Exporter E-mail Address
 * - Box 36 - Exporter Telephone Number
 * - Box 37 - Printed Name
 * - Box 38 - Signature
 * - Box 39 - Title
 *
 * Box 40 - Date IS DYNAMIC.
 *
 * ================================================================
 * IMPORTANT
 * ================================================================
 *
 * Before running:
 *
 * 1. Set TEMPLATE_DOC_ID
 * 2. Set OUTPUT_FOLDER_ID
 *
 */


const CONFIG = Object.freeze({

  SHEET_NAME: 'SLI Control',

  // Native Google Docs master template ID
  TEMPLATE_DOC_ID: 'YOUR_GOOGLE_DOC_TEMPLATE_ID',

  // Google Drive destination folder ID
  OUTPUT_FOLDER_ID: 'YOUR_OUTPUT_FOLDER_ID',

  MAX_COMMODITIES: 5,

  SCHEMA_VERSION: '1.3'

});


const MIME = Object.freeze({

  DOCX:
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',

  PDF:
    'application/pdf'

});


/**
 * Cargo Insurance remains automated.
 *
 * Insurance Requested is always YES.
 */
const CHECKED = '☒';
const UNCHECKED = '☐';


/**
 * ================================================================
 * FORBIDDEN STATIC TEMPLATE TOKENS
 * ================================================================
 *
 * These placeholders MUST NOT exist in the production Google Docs
 * master because these fields are controlled directly by the master.
 */

const FORBIDDEN_STATIC_TOKENS = Object.freeze([

  '<<B8_RELATED>>',
  '<<B8_UNRELATED>>',

  '<<B9_YES>>',
  '<<B9_NO>>',

  '<<B10_YES>>',
  '<<B10_NO>>',

  '<<B12_DIRECT>>',
  '<<B12_GOVERNMENT>>',
  '<<B12_RESELLER>>',
  '<<B12_OTHER>>',

  '<<B15_YES>>',
  '<<B15_NO>>',

  '<<B16_YES>>',
  '<<B16_NO>>',

  '<<MODE_AIR>>',
  '<<MODE_OCEAN>>',
  '<<MODE_RAIL>>',
  '<<MODE_TRUCK>>',

  '<<INC_EXW>>',
  '<<INC_FCA>>',
  '<<INC_FAS>>',
  '<<INC_FOB>>',
  '<<INC_CFR>>',
  '<<INC_CIF>>',
  '<<INC_CPT>>',
  '<<INC_CIP>>',
  '<<INC_DAP>>',
  '<<INC_DPU>>',
  '<<INC_DDP>>',

  '<<B30_DDTC_REGISTRATION>>',

  '<<B31_YES>>',
  '<<B31_NO>>',

  '<<B32_CHECK>>',

  '<<B35_EMAIL>>',
  '<<B36_PHONE>>',
  '<<B37_NAME>>',
  '<<B38_SIGNATURE>>',
  '<<B39_TITLE>>'

]);


/**
 * ================================================================
 * FORBIDDEN STATIC JSON FIELDS
 * ================================================================
 *
 * Gemini must NOT send these fields in schema version 1.3.
 */

const FORBIDDEN_STATIC_JSON_FIELDS = Object.freeze([

  'box_8_related_party',

  'box_9_routed_export_transaction',

  'box_10_hazardous_material',

  'box_12_ultimate_consignee_type',

  'box_15_carnet',

  'box_16_tib',

  'mode_of_transport',

  'incoterm_2020',

  'box_30_ddtc_registration_number',

  'box_31_eligible_party_certification',

  'box_32_low_value_aes_indicator',

  'box_35_exporter_email',

  'box_36_exporter_phone',

  'box_37_printed_name',

  'box_38_signature',

  'box_39_title'

]);


/**
 * ================================================================
 * MENU
 * ================================================================
 */

function onOpen() {

  SpreadsheetApp
    .getUi()
    .createMenu('SLI Automation')
    .addItem(
      '1. Setup Control Sheet',
      'setupControlSheet'
    )
    .addItem(
      '2. Validate Master Template',
      'validateMasterTemplate'
    )
    .addSeparator()
    .addItem(
      '3. Generate SLI from Active Row',
      'generateSLIFromActiveRow'
    )
    .addToUi();

}


/**
 * ================================================================
 * CONTROL SHEET SETUP
 * ================================================================
 */

function setupControlSheet() {

  const ss =
    SpreadsheetApp.getActiveSpreadsheet();

  let sheet =
    ss.getSheetByName(
      CONFIG.SHEET_NAME
    );


  if (!sheet) {

    sheet =
      ss.insertSheet(
        CONFIG.SHEET_NAME
      );

  }


  const headers = [[

    'Shipment ID',

    'Gem JSON Payload',

    'Automation Status',

    'Google Doc',

    'DOCX',

    'PDF',

    'Generated At'

  ]];


  sheet
    .getRange(
      1,
      1,
      1,
      headers[0].length
    )
    .setValues(
      headers
    );


  sheet
    .getRange(
      1,
      1,
      1,
      headers[0].length
    )
    .setFontWeight(
      'bold'
    );


  sheet.setFrozenRows(
    1
  );


  sheet.setColumnWidth(
    1,
    160
  );

  sheet.setColumnWidth(
    2,
    600
  );

  sheet.setColumnWidth(
    3,
    220
  );

  sheet.setColumnWidth(
    4,
    280
  );

  sheet.setColumnWidth(
    5,
    280
  );

  sheet.setColumnWidth(
    6,
    280
  );

  sheet.setColumnWidth(
    7,
    180
  );


  sheet
    .getRange(
      'B:B'
    )
    .setWrap(
      true
    );


  sheet
    .getRange(
      'C:G'
    )
    .setWrap(
      true
    );


  SpreadsheetApp
    .getUi()
    .alert(

      'SLI Control is ready.\n\n' +

      'Paste one READY_FOR_AUTOMATION JSON payload into column B, starting at row 2.'

    );

}


/**
 * ================================================================
 * MASTER TEMPLATE VALIDATION
 * ================================================================
 */

function validateMasterTemplate() {

  assertConfigured_();


  const validation =
    inspectMasterTemplate_();


  if (

    validation.missingRequired.length > 0 ||

    validation.forbiddenStatic.length > 0 ||

    validation.oldPlaceholderSyntax

  ) {

    throw new Error(

      buildTemplateValidationError_(
        validation
      )

    );

  }


  SpreadsheetApp
    .getUi()
    .alert(

      'Master template validation PASSED.\n\n' +

      validation.requiredCount +

      ' dynamic placeholders were found.\n\n' +

      'Static master fields are protected and no automation placeholders were detected inside them.'

    );

}


/**
 * ================================================================
 * GENERATE SLI
 * ================================================================
 */

function generateSLIFromActiveRow() {

  const ss =
    SpreadsheetApp.getActiveSpreadsheet();


  const sheet =
    ss.getSheetByName(
      CONFIG.SHEET_NAME
    );


  if (!sheet) {

    throw new Error(

      'Sheet "' +

      CONFIG.SHEET_NAME +

      '" does not exist. Run Setup Control Sheet first.'

    );

  }


  const row =
    sheet
      .getActiveCell()
      .getRow();


  if (row < 2) {

    throw new Error(

      'Select a shipment row below the header row.'

    );

  }


  try {


    assertConfigured_();


    sheet
      .getRange(
        row,
        3
      )
      .setValue(
        'VALIDATING'
      );


    /**
     * ============================================================
     * READ JSON
     * ============================================================
     */

    const rawJson =
      String(

        sheet
          .getRange(
            row,
            2
          )
          .getValue() || ''

      )
      .trim();


    if (!rawJson) {

      throw new Error(

        'Column B does not contain a Gem JSON payload.'

      );

    }


    const payload =
      parseGemJson_(
        rawJson
      );


    /**
     * ============================================================
     * VALIDATE PAYLOAD
     * ============================================================
     */

    validatePayload_(
      payload
    );


    sheet
      .getRange(
        row,
        1
      )
      .setValue(
        payload.shipment_id
      );


    /**
     * ============================================================
     * VALIDATE MASTER
     * ============================================================
     */

    validateTemplateWithoutAlert_();


    sheet
      .getRange(
        row,
        3
      )
      .setValue(
        'GENERATING'
      );


    /**
     * ============================================================
     * CREATE COPY OF MASTER
     * ============================================================
     */

    const outputFolder =
      DriveApp
        .getFolderById(
          CONFIG.OUTPUT_FOLDER_ID
        );


    const baseName =
      buildOutputName_(
        payload
      );


    const masterFile =
      DriveApp
        .getFileById(
          CONFIG.TEMPLATE_DOC_ID
        );


    const workingCopy =
      masterFile
        .makeCopy(

          baseName,

          outputFolder

        );


    const workingDocId =
      workingCopy
        .getId();


    const doc =
      DocumentApp
        .openById(
          workingDocId
        );


    const body =
      doc
        .getBody();


    /**
     * ============================================================
     * VARIABLE FIELDS ONLY
     * ============================================================
     */

    const replacements =
      buildMainReplacements_(
        payload
      );


    Object
      .keys(
        replacements
      )
      .forEach(

        token => {

          replaceToken_(

            body,

            token,

            replacements[token]

          );

        }

      );


    /**
     * ============================================================
     * COMMODITY TABLE
     * ============================================================
     */

    populateCommodityRows_(

      body,

      payload.sli.commodities

    );


    /**
     * IMPORTANT:
     *
     * Boxes 8, 9, 10, 12, 15, 16,
     * Mode of Transport,
     * Incoterms,
     * 30, 31, 32,
     * 35, 36, 37, 38 and 39
     *
     * ARE NEVER TOUCHED.
     */


    doc.saveAndClose();


    /**
     * Give Google Docs a moment to persist edits.
     */
    Utilities.sleep(
      1000
    );


    /**
     * ============================================================
     * DOCUMENT QA
     * ============================================================
     */

    const qaDoc =
      DocumentApp
        .openById(
          workingDocId
        );


    const finalText =
      qaDoc
        .getBody()
        .getText();


    qaDoc.saveAndClose();


    /**
     * No dynamic placeholders may remain.
     */
    const remainingTokens =
      finalText.match(
        /<<[^<>]+>>/g
      ) || [];


    if (
      remainingTokens.length > 0
    ) {

      throw new Error(

        'DOCUMENT QA FAILED.\n\n' +

        'Unresolved placeholders remain:\n' +

        [
          ...new Set(
            remainingTokens
          )
        ]
        .join('\n') +

        '\n\nDOCX and PDF were NOT exported.'

      );

    }


    /**
     * Old Gemini test placeholders must not remain.
     */
    if (

      finalText.includes('{{') ||

      finalText.includes('}}')

    ) {

      throw new Error(

        'DOCUMENT QA FAILED.\n\n' +

        'Old {{ ... }} placeholder syntax was found in the generated document.\n\n' +

        'DOCX and PDF were NOT exported.'

      );

    }


    /**
     * ============================================================
     * EXPORT
     * ============================================================
     */

    Utilities.sleep(
      1000
    );


    const docxBlob =
      exportGoogleWorkspaceFile_(

        workingDocId,

        MIME.DOCX

      )
      .setName(

        baseName +
        '.docx'

      );


    const pdfBlob =
      exportGoogleWorkspaceFile_(

        workingDocId,

        MIME.PDF

      )
      .setName(

        baseName +
        '.pdf'

      );


    const docxFile =
      outputFolder
        .createFile(
          docxBlob
        );


    const pdfFile =
      outputFolder
        .createFile(
          pdfBlob
        );


    /**
     * ============================================================
     * WRITE OUTPUT LINKS
     * ============================================================
     */

    sheet
      .getRange(
        row,
        3
      )
      .setValue(
        'COMPLETED'
      );


    sheet
      .getRange(
        row,
        4
      )
      .setValue(
        workingCopy.getUrl()
      );


    sheet
      .getRange(
        row,
        5
      )
      .setValue(
        docxFile.getUrl()
      );


    sheet
      .getRange(
        row,
        6
      )
      .setValue(
        pdfFile.getUrl()
      );


    sheet
      .getRange(
        row,
        7
      )
      .setValue(
        new Date()
      );


    SpreadsheetApp
      .getUi()
      .alert(

        'SLI generation completed successfully.\n\n' +

        'Google Doc, DOCX and PDF links were written to the active row.'

      );


  } catch (error) {


    sheet
      .getRange(
        row,
        3
      )
      .setValue(

        'ERROR: ' +
        error.message

      );


    throw error;

  }

}


/**
 * ================================================================
 * GEM JSON PARSER
 * ================================================================
 *
 * Allows JSON copied directly from Gemini even if it includes:
 *
 * ```json
 * { ... }
 * ```
 */

function parseGemJson_(
  raw
) {

  let text =
    raw.trim();


  text =
    text
      .replace(
        /^```json\s*/i,
        ''
      )
      .replace(
        /^```\s*/i,
        ''
      )
      .replace(
        /```\s*$/i,
        ''
      )
      .trim();


  const firstBrace =
    text.indexOf(
      '{'
    );


  const lastBrace =
    text.lastIndexOf(
      '}'
    );


  if (

    firstBrace === -1 ||

    lastBrace === -1 ||

    lastBrace <= firstBrace

  ) {

    throw new Error(

      'No valid JSON object was found in column B.'

    );

  }


  text =
    text.substring(

      firstBrace,

      lastBrace + 1

    );


  try {

    return JSON.parse(
      text
    );

  }

  catch (error) {

    throw new Error(

      'Invalid JSON: ' +

      error.message

    );

  }

}


/**
 * ================================================================
 * PAYLOAD VALIDATION
 * ================================================================
 */

function validatePayload_(
  payload
) {


  assert_(

    payload &&
    typeof payload === 'object',

    'Payload is missing.'

  );


  /**
   * Schema
   */
  assert_(

    payload.schema_version ===
      CONFIG.SCHEMA_VERSION,

    'Unsupported schema_version. Expected ' +

      CONFIG.SCHEMA_VERSION +

      '.'

  );


  /**
   * Status
   */
  assert_(

    payload.status ===
      'READY_FOR_AUTOMATION',

    'Gem status is not READY_FOR_AUTOMATION.'

  );


  /**
   * Missing fields
   */
  assert_(

    Array.isArray(
      payload.missing_fields
    ) &&

    payload.missing_fields.length ===
      0,

    'missing_fields is not empty.'

  );


  /**
   * Conflicts
   */
  assert_(

    Array.isArray(
      payload.conflicts
    ) &&

    payload.conflicts.length ===
      0,

    'conflicts is not empty.'

  );


  /**
   * Shipment ID
   */
  assert_(

    typeof payload.shipment_id ===
      'string' &&

    payload.shipment_id.trim() !==
      '',

    'shipment_id is required.'

  );


  /**
   * SLI object
   */
  const s =
    payload.sli;


  assert_(

    s &&
    typeof s === 'object',

    'sli object is missing.'

  );


  /**
   * ============================================================
   * STATIC FIELDS MUST NOT EXIST IN JSON
   * ============================================================
   */

  FORBIDDEN_STATIC_JSON_FIELDS
    .forEach(

      field => {

        assert_(

          !Object.prototype
            .hasOwnProperty
            .call(
              s,
              field
            ),

          'Static master field "' +

            field +

            '" must NOT appear in schema 1.3 JSON.'

        );

      }

    );


  /**
   * ============================================================
   * CARGO INSURANCE
   * ============================================================
   */

  assert_(

    s.cargo_insurance_requested ===
      true,

    'Cargo Insurance Requested must be true.'

  );


  assertNumber_(

    s.cargo_insurance_amount_usd,

    'cargo_insurance_amount_usd',

    true

  );


  /**
   * ============================================================
   * REQUIRED VARIABLE STRING FIELDS
   * ============================================================
   */

  const requiredStrings = [

    'box_1_exporter_name',

    'box_2_exporter_address',

    'box_3_freight_location_company',

    'box_6_exporter_ein',

    'box_7_exporter_reference',

    'box_11_ultimate_consignee',

    'box_14_country_destination',

    'named_place_or_port',

    'box_40_date'

  ];


  requiredStrings
    .forEach(

      key => {

        assert_(

          typeof s[key] ===
            'string' &&

          s[key].trim() !==
            '',

          key +
          ' is required.'

        );

      }

    );


  /**
   * ============================================================
   * COMMODITY ARRAY
   * ============================================================
   */

  assert_(

    Array.isArray(
      s.commodities
    ),

    'commodities must be an array.'

  );


  assert_(

    s.commodities.length >=
      1,

    'At least one commodity is required.'

  );


  assert_(

    s.commodities.length <=
      CONFIG.MAX_COMMODITIES,

    'The template supports a maximum of ' +

      CONFIG.MAX_COMMODITIES +

      ' commodity lines.'

  );


  /**
   * ============================================================
   * EACH COMMODITY
   * ============================================================
   */

  s.commodities
    .forEach(

      (
        item,
        index
      ) => {


        const n =
          index + 1;


        /**
         * Country of manufacture
         */
        assert_(

          typeof item.country_of_manufacture ===
            'string' &&

          item.country_of_manufacture.trim() !==
            '',

          'Commodity ' +

          n +

          ': country_of_manufacture is required.'

        );


        /**
         * Box 20
         */
        assertEnum_(

          item.box_20_origin,

          [
            'Domestic',
            'Foreign'
          ],

          'Commodity ' +

          n +

          ': box_20_origin'

        );


        /**
         * Box 21 classification
         */
        assert_(

          typeof item.box_21_hts_or_schedule_b ===
            'string' &&

          item.box_21_hts_or_schedule_b.trim() !==
            '',

          'Commodity ' +

          n +

          ': Box 21 classification is required.'

        );


        /**
         * Box 21 description
         */
        assert_(

          typeof item.box_21_description ===
            'string' &&

          item.box_21_description.trim() !==
            '',

          'Commodity ' +

          n +

          ': Box 21 description is required.'

        );


        /**
         * Box 22 quantity
         */
        assertNumber_(

          item.box_22_quantity,

          'Commodity ' +

          n +

          ': box_22_quantity',

          true

        );


        /**
 * Box 22 quantity
 */
assertNumber_(

  item.box_22_quantity,

  'Commodity ' +

  n +

  ': box_22_quantity',

  true

);


/**
 * Box 23 unit
 */
assert_(

  typeof item.box_23_unit ===
    'string' &&

  item.box_23_unit.trim() !==
    '',

  'Commodity ' +

  n +

  ': box_23_unit is required.'

);



        /**
         * Box 24
         */
        assertNumber_(

          item.box_24_shipping_weight_kg,

          'Commodity ' +

          n +

          ': box_24_shipping_weight_kg',

          true

        );


        /**
         * Box 25
         */
        assert_(

          typeof item.box_25_export_classification ===
            'string' &&

          item.box_25_export_classification.trim() !==
            '',

          'Commodity ' +

          n +

          ': Box 25 is required.'

        );


        /**
         * Box 26
         */
        assertEnum_(

          item.box_26_sme,

          [
            'Y',
            'N'
          ],

          'Commodity ' +

          n +

          ': box_26_sme'

        );


        /**
         * Box 27
         */
        assert_(

          typeof item.box_27_export_authorization ===
            'string' &&

          item.box_27_export_authorization.trim() !==
            '',

          'Commodity ' +

          n +

          ': Box 27 is required.'

        );


        /**
         * Box 28
         */
        assertNumber_(

          item.box_28_value_usd,

          'Commodity ' +

          n +

          ': box_28_value_usd',

          false

        );


        /**
         * Box 29 - optional / nullable
         */
        if (

          item.box_29_license_value_usd !==
            null

        ) {

          assertNumber_(

            item.box_29_license_value_usd,

            'Commodity ' +

            n +

            ': box_29_license_value_usd',

            false

          );

        }


      }

    );

}


/**
 * ================================================================
 * MAIN VARIABLE FIELD REPLACEMENTS
 * ================================================================
 *
 * STATIC MASTER FIELDS ARE INTENTIONALLY ABSENT.
 */

function buildMainReplacements_(
  payload
) {

  const s =
    payload.sli;


  return {


    /**
     * Box 1
     */
    '<<B1_EXPORTER_NAME>>':
      s.box_1_exporter_name,


    /**
     * Box 2
     */
    '<<B2_EXPORTER_ADDRESS>>':
      s.box_2_exporter_address,


    /**
     * Box 3
     */
    '<<B3_FREIGHT_COMPANY>>':
      s.box_3_freight_location_company,


    /**
     * Box 4
     */
    '<<B4_FREIGHT_ADDRESS>>':
      renderNA_(
        s.box_4_freight_location_address
      ),


    /**
     * Box 5
     */
    '<<B5_STATE_ORIGIN>>':
      renderNA_(
        s.box_5_state_of_origin
      ),


    /**
     * Box 6
     */
    '<<B6_EXPORTER_EIN>>':
      s.box_6_exporter_ein,


    /**
     * Box 7
     */
    '<<B7_EXPORTER_REFERENCE>>':
      s.box_7_exporter_reference,


    /**
     * Boxes 8, 9, 10 are STATIC
     * and intentionally absent.
     */


    /**
     * Box 11
     */
    '<<B11_ULTIMATE_CONSIGNEE>>':
      s.box_11_ultimate_consignee,


    /**
     * Box 12 is STATIC.
     */


    /**
     * Box 13
     */
    '<<B13_INTERMEDIATE_CONSIGNEE>>':
      renderNA_(
        s.box_13_intermediate_consignee
      ),


    /**
     * Box 14
     */
    '<<B14_DESTINATION_COUNTRY>>':
      s.box_14_country_destination,


    /**
     * Boxes 15 and 16 are STATIC.
     */


    /**
     * Box 17
     */
    '<<B17_ENTRY_NUMBER>>':
      renderNA_(
        s.box_17_entry_number
      ),


    /**
     * Box 18
     */
    '<<B18_IN_BOND_CODE>>':
      renderNA_(
        s.box_18_in_bond_code
      ),


    /**
     * Box 19
     */
    '<<B19_FTZ_IDENTIFIER>>':
      renderNA_(
        s.box_19_ftz_identifier
      ),


    /**
     * Instructions to Forwarder
     */
    '<<INSTRUCTIONS_TO_FORWARDER>>':
      renderNA_(
        s.instructions_to_forwarder
      ),


    /**
     * Cargo Insurance
     *
     * Always:
     *
     * No  = unchecked
     * Yes = checked
     */
    '<<INSURANCE_NO>>':
      UNCHECKED,


    '<<INSURANCE_YES>>':
      CHECKED,


    '<<INSURANCE_AMOUNT>>':
      formatMoney_(
        s.cargo_insurance_amount_usd
      ),


    /**
     * Mode of Transport is STATIC.
     */


    /**
     * Incoterms 2020 are STATIC.
     */


    /**
     * Named Place or Port
     */
    '<<NAMED_PLACE_OR_PORT>>':
      s.named_place_or_port,


    /**
     * Boxes 30-32 are STATIC.
     */


    /**
     * Boxes 35-39 are STATIC.
     */


    /**
     * Box 40 is DYNAMIC.
     */
    '<<B40_DATE>>':
      s.box_40_date


  };

}


/**
 * ================================================================
 * COMMODITY ROWS 20-29
 * ================================================================
 */

function populateCommodityRows_(
  body,
  commodities
) {


  for (

    let i = 1;

    i <= CONFIG.MAX_COMMODITIES;

    i++

  ) {


    const item =
      commodities[
        i - 1
      ];


    /**
     * ============================================================
     * UNUSED ROW
     * ============================================================
     */

    if (!item) {


      for (

        let box = 20;

        box <= 29;

        box++

      ) {


        replaceToken_(

          body,

          `<<I${i}_B${box}>>`,

          ''

        );


      }


      continue;

    }


    /**
     * ============================================================
     * BOX 20
     * ============================================================
     */

    replaceToken_(

      body,

      `<<I${i}_B20>>`,

      item.box_20_origin

    );


    /**
     * ============================================================
     * BOX 21
     * ============================================================
     */

    replaceToken_(

      body,

      `<<I${i}_B21>>`,

      item.box_21_hts_or_schedule_b +

      '\n' +

      item.box_21_description

    );


    /**
    * ============================================================
    * BOX 22 - QUANTITY ONLY
    * ============================================================
    *
    * Example:
    * 101
    * 202
   *
   * Do NOT include the unit here.
   */
    replaceToken_(

   body,

   `<<I${i}_B22>>`,

   String(
    item.box_22_quantity
   )

    );



    /**
 * ============================================================
 * BOX 23 - UNIT OF MEASURE
 * ============================================================
 *
 * For this SLI workflow, Box 23 displays the unit associated
 * with the quantity reported in Box 22.
 *
 * Example:
 * Piece
 */
replaceToken_(

  body,

  `<<I${i}_B23>>`,

  item.box_23_unit

);




    /**
     * ============================================================
     * BOX 24
     * ============================================================
     */

    replaceToken_(

      body,

      `<<I${i}_B24>>`,

      formatNumber_(
        item.box_24_shipping_weight_kg
      )

    );


    /**
     * ============================================================
     * BOX 25
     * ============================================================
     */

    replaceToken_(

      body,

      `<<I${i}_B25>>`,

      item.box_25_export_classification

    );


    /**
     * ============================================================
     * BOX 26
     * ============================================================
     */

    replaceToken_(

      body,

      `<<I${i}_B26>>`,

      item.box_26_sme

    );


    /**
     * ============================================================
     * BOX 27
     * ============================================================
     */

    replaceToken_(

      body,

      `<<I${i}_B27>>`,

      item.box_27_export_authorization

    );


    /**
     * ============================================================
     * BOX 28
     * ============================================================
     */

    replaceToken_(

      body,

      `<<I${i}_B28>>`,

      formatMoney_(
        item.box_28_value_usd
      )

    );


    /**
     * ============================================================
     * BOX 29
     * ============================================================
     */

    replaceToken_(

      body,

      `<<I${i}_B29>>`,

      item.box_29_license_value_usd ===
        null

        ? 'N/A'

        :

        formatMoney_(
          item.box_29_license_value_usd
        )

    );


  }

}


/**
 * ================================================================
 * TOKEN REPLACEMENT
 * ================================================================
 */

function replaceToken_(
  body,
  token,
  value
) {


  const pattern =
    escapeRegex_(
      token
    );


  const replacement =
    escapeReplacement_(

      String(
        value ?? ''
      )

    );


  body.replaceText(

    pattern,

    replacement

  );

}


/**
 * ================================================================
 * GOOGLE DRIVE EXPORT
 * ================================================================
 */

function exportGoogleWorkspaceFile_(
  fileId,
  mimeType
) {


  const url =

    'https://www.googleapis.com/drive/v3/files/' +

    encodeURIComponent(
      fileId
    ) +

    '/export?mimeType=' +

    encodeURIComponent(
      mimeType
    );


  const response =
    UrlFetchApp.fetch(

      url,

      {

        headers: {

          Authorization:

            'Bearer ' +

            ScriptApp.getOAuthToken()

        },

        muteHttpExceptions:
          true

      }

    );


  const code =
    response.getResponseCode();


  if (
    code !== 200
  ) {


    throw new Error(

      'Drive export failed. HTTP ' +

      code +

      ': ' +

      response.getContentText()

    );


  }


  return response.getBlob();

}


/**
 * ================================================================
 * MASTER TEMPLATE INSPECTION
 * ================================================================
 */

function inspectMasterTemplate_() {


  const doc =
    DocumentApp
      .openById(
        CONFIG.TEMPLATE_DOC_ID
      );


  const bodyText =
    doc
      .getBody()
      .getText();


  const required =
    getRequiredTemplateTokens_();


  /**
   * Required dynamic tokens missing?
   */
  const missingRequired =
    required.filter(

      token =>
        !bodyText.includes(
          token
        )

    );


  /**
   * Static tokens accidentally left in master?
   */
  const forbiddenStatic =
    FORBIDDEN_STATIC_TOKENS.filter(

      token =>
        bodyText.includes(
          token
        )

    );


  /**
   * Old Gemini placeholder format?
   */
  const oldPlaceholderSyntax =

    bodyText.includes('{{') ||

    bodyText.includes('}}');


  return {

    requiredCount:
      required.length,

    missingRequired:
      missingRequired,

    forbiddenStatic:
      forbiddenStatic,

    oldPlaceholderSyntax:
      oldPlaceholderSyntax

  };

}


/**
 * ================================================================
 * SILENT MASTER VALIDATION
 * ================================================================
 */

function validateTemplateWithoutAlert_() {


  const validation =
    inspectMasterTemplate_();


  if (

    validation.missingRequired.length > 0 ||

    validation.forbiddenStatic.length > 0 ||

    validation.oldPlaceholderSyntax

  ) {


    throw new Error(

      buildTemplateValidationError_(
        validation
      )

    );


  }

}


/**
 * ================================================================
 * TEMPLATE VALIDATION ERROR MESSAGE
 * ================================================================
 */

function buildTemplateValidationError_(
  validation
) {


  let message =

    'MASTER TEMPLATE VALIDATION FAILED.\n';


  /**
   * Missing dynamic placeholders
   */
  if (

    validation.missingRequired.length >
      0

  ) {


    message +=

      '\nMissing required dynamic placeholders:\n' +

      validation.missingRequired.join(
        '\n'
      ) +

      '\n';

  }


  /**
   * Static placeholders should not exist.
   */
  if (

    validation.forbiddenStatic.length >
      0

  ) {


    message +=

      '\nStatic-field placeholders were found but must NOT exist.\n\n' +

      'These fields must be configured directly in the Google Docs master:\n\n' +

      validation.forbiddenStatic.join(
        '\n'
      ) +

      '\n';

  }


  /**
   * Old placeholder syntax.
   */
  if (
    validation.oldPlaceholderSyntax
  ) {


    message +=

      '\nOld {{ ... }} placeholders were detected.\n\n' +

      'Production placeholders must use only << ... >> syntax.\n';

  }


  return message;

}


/**
 * ================================================================
 * REQUIRED DYNAMIC TEMPLATE TOKENS
 * ================================================================
 *
 * IMPORTANT:
 *
 * Boxes 8, 9, 10, 12, 15, 16,
 * Mode,
 * Incoterms,
 * Boxes 30-32,
 * Boxes 35-39
 *
 * ARE INTENTIONALLY ABSENT.
 *
 * Box 40 IS included.
 */

function getRequiredTemplateTokens_() {


  const tokens = [


    /**
     * Boxes 1-7
     */
    '<<B1_EXPORTER_NAME>>',

    '<<B2_EXPORTER_ADDRESS>>',

    '<<B3_FREIGHT_COMPANY>>',

    '<<B4_FREIGHT_ADDRESS>>',

    '<<B5_STATE_ORIGIN>>',

    '<<B6_EXPORTER_EIN>>',

    '<<B7_EXPORTER_REFERENCE>>',


    /**
     * Box 11
     */
    '<<B11_ULTIMATE_CONSIGNEE>>',


    /**
     * Boxes 13-14
     */
    '<<B13_INTERMEDIATE_CONSIGNEE>>',

    '<<B14_DESTINATION_COUNTRY>>',


    /**
     * Boxes 17-19
     */
    '<<B17_ENTRY_NUMBER>>',

    '<<B18_IN_BOND_CODE>>',

    '<<B19_FTZ_IDENTIFIER>>',


    /**
     * Instructions
     */
    '<<INSTRUCTIONS_TO_FORWARDER>>',


    /**
     * Cargo Insurance
     */
    '<<INSURANCE_NO>>',

    '<<INSURANCE_YES>>',

    '<<INSURANCE_AMOUNT>>',


    /**
     * Named place / port
     */
    '<<NAMED_PLACE_OR_PORT>>',


    /**
     * Box 40 Date
     */
    '<<B40_DATE>>'


  ];


  /**
   * ============================================================
   * FIVE COMMODITY ROWS
   * ============================================================
   *
   * Each row has:
   *
   * Boxes 20-29
   */

  for (

    let item = 1;

    item <= CONFIG.MAX_COMMODITIES;

    item++

  ) {


    for (

      let box = 20;

      box <= 29;

      box++

    ) {


      tokens.push(

        `<<I${item}_B${box}>>`

      );


    }


  }


  return tokens;

}


/**
 * ================================================================
 * OUTPUT FILE NAME
 * ================================================================
 */

function buildOutputName_(
  payload
) {


  const country =

    payload
      .sli
      .box_14_country_destination

      ||

    'Destination';


  const today =

    Utilities.formatDate(

      new Date(),

      Session.getScriptTimeZone(),

      'yyyy-MM-dd'

    );


  return sanitizeFilename_(

    'SLI_' +

    payload.shipment_id +

    '_' +

    country +

    '_' +

    today

  );

}


/**
 * ================================================================
 * RENDER N/A
 * ================================================================
 */

function renderNA_(
  value
) {


  return (

    value === null ||

    value === undefined ||

    value === ''

  )

    ? 'N/A'

    : String(
        value
      );

}


/**
 * ================================================================
 * MONEY FORMAT
 * ================================================================
 */

function formatMoney_(
  value
) {


  const number =
    Number(
      value
    );


  if (
    !Number.isFinite(
      number
    )
  ) {


    throw new Error(

      'Invalid monetary value: ' +

      value

    );


  }


  return number.toLocaleString(

    'en-US',

    {

      minimumFractionDigits:
        2,

      maximumFractionDigits:
        2

    }

  );

}


/**
 * ================================================================
 * NUMBER FORMAT
 * ================================================================
 */

function formatNumber_(
  value
) {


  const number =
    Number(
      value
    );


  if (
    !Number.isFinite(
      number
    )
  ) {


    throw new Error(

      'Invalid numeric value: ' +

      value

    );


  }


  return number.toLocaleString(

    'en-US',

    {

      maximumFractionDigits:
        4

    }

  );

}


/**
 * ================================================================
 * NUMBER VALIDATION
 * ================================================================
 */

function assertNumber_(
  value,
  field,
  mustBePositive
) {


  /**
   * Null, undefined and empty strings are NOT valid numbers.
   */
  assert_(

    value !== null &&

    value !== undefined &&

    value !== '',

    field +
    ' is required.'

  );


  const number =
    Number(
      value
    );


  assert_(

    Number.isFinite(
      number
    ),

    field +
    ' must be numeric.'

  );


  if (
    mustBePositive
  ) {


    assert_(

      number > 0,

      field +
      ' must be greater than zero.'

    );


  } else {


    assert_(

      number >= 0,

      field +
      ' cannot be negative.'

    );


  }

}


/**
 * ================================================================
 * ENUM VALIDATION
 * ================================================================
 */

function assertEnum_(
  value,
  allowed,
  field
) {


  assert_(

    allowed.includes(
      value
    ),

    field +

    ' must be one of: ' +

    allowed.join(
      ', '
    )

  );

}


/**
 * ================================================================
 * GENERIC ASSERT
 * ================================================================
 */

function assert_(
  condition,
  message
) {


  if (
    !condition
  ) {


    throw new Error(
      message
    );


  }

}


/**
 * ================================================================
 * CONFIGURATION VALIDATION
 * ================================================================
 */

function assertConfigured_() {


  assert_(

    CONFIG.TEMPLATE_DOC_ID &&

    !CONFIG.TEMPLATE_DOC_ID.includes(
      'PASTE_'
    ),

    'Configure TEMPLATE_DOC_ID in Code.gs.'

  );


  assert_(

    CONFIG.OUTPUT_FOLDER_ID &&

    !CONFIG.OUTPUT_FOLDER_ID.includes(
      'PASTE_'
    ),

    'Configure OUTPUT_FOLDER_ID in Code.gs.'

  );

}


/**
 * ================================================================
 * REGEX ESCAPE
 * ================================================================
 */

function escapeRegex_(
  text
) {


  return String(
    text
  )
  .replace(

    /[.*+?^${}()|[\]\\]/g,

    '\\$&'

  );

}


/**
 * ================================================================
 * REPLACEMENT ESCAPE
 * ================================================================
 */

function escapeReplacement_(
  text
) {


  return String(
    text
  )
  .replace(

    /\\/g,

    '\\\\'

  )
  .replace(

    /\$/g,

    '\\$'

  );

}


/**
 * ================================================================
 * SAFE FILE NAME
 * ================================================================
 */

function sanitizeFilename_(
  name
) {


  return String(
    name
  )
  .replace(

    /[\\/:*?"<>|#%{}]/g,

    '-'

  )
  .replace(

    /\s+/g,

    '_'

  )
  .substring(
    0,
    180
  );

}
